### ISSUE TITLE
Exit status 2

### ISSUE THREAD

**Issue by c26ranto** [yagizzcann/whatsapp-api-go#1]
goroutine 1 [running]:
main.main()
	d:/Project/WebAPI/wago/main.go:23 +0x1f2
exit status 2

[Done] exited with code=1 in 3.931 seconds

**Comment by yagizzcann** [comment]
This issuse fixed in commit [#bb7b7470](https://github.com/yagizzcann/whatsapp-api-go/commit/bb7b7470bb106ce5440ffdf45fab4963421a769f)

Plase get latest version of package
